name = "remix"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
#predev = "npx prisma generate"
#dev = "npx prisma migrate deploy && npm exec remix vite:dev"
dev = "npm exec remix vite:dev"

port=5500 # add this param to force a port on a static cloudflared tunnel